				</div>

			<!-- Main -->
				<div class="wrapper">
					<div class="container" id="main">

						<!-- Content -->
							<article id="content">
								<header>
									<h2>Buscador Lider</h2>
									<br>
									<form action="protected/php/buscadorLider.php" method="POST">
										<div class="row 50%">
											<div class="8u 12u(mobile)">
												<input name="txtBusqueda" placeholder="Nombre" type="text" autocomplete="on" id="liderAuto" autofocus/>
											</div>
											<div class="4u 12u(mobile)">
												<input type="submit" value="Buscar" />
											</div>
										</div>
									</form>
								</header>
								<!-- <a href="#" class="image featured"><img src="images/quien_Logo_Kamila.png" alt="" /></a>
								<h2>Texto X</h2>	
								<p>Texto X</p> -->
							</article>