				</div>

			<!-- Main -->
				<div class="wrapper">
					<div class="container" id="main">

						<!-- Content -->
							<!-- <article id="content">
								<header>
									<h2>Titulo/h2>
									<p>Sub Titulo</p>
								</header>
								<a href="#" class="image featured"><img src="images/quien_Logo_Kamila.png" alt="" /></a>
								<h2>Texto X</h2>	
								<p>Texto X</p>
							</article> -->