<!-- Footer -->
				<div id="footer-wrapper">
					<div id="copyright" class="container">
						<ul class="menu">
							<li>&copy; X. Todos los derechos reservados.</li><li>Diseñado por: <a href="#">X</a></li>
						</ul>
					</div>
				</div>

		</div>

			<!-- Script AutoCompletado -->

			

			<script>

		        $( "#seccAuto" ).autocomplete({
		          delay: 0,
		          source: "../protected/php/seccAuto.php"
		        });

		    </script>

		    <script>

		        $( "#codigoAuto" ).autocomplete({
		          delay: 0,
		          source: "../protected/php/codigoAuto.php"
		        });

		    </script>

			<script>

		        $( "#coloniaAuto" ).autocomplete({
		          delay: 0,
		          source: "../protected/php/autoCol.php"
		        });

		    </script>
		    <script>

		        $( "#liderAuto" ).autocomplete({
		          delay: 0,
		          source: "../protected/php/autoLider.php"
		        });

		    </script>
		    <script>

		        $( "#inviAuto" ).autocomplete({
		          delay: 0,
		          source: "../protected/php/autoInvi.php"
		        });

		    </script>
		    <!-- Script AutoCompletado -->

		<!-- Scripts -->

			
			<script src="../assets/js/jquery.dropotron.min.js"></script>
			<script src="../assets/js/skel.min.js"></script>
			<script src="../assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="../assets/js/main.js"></script>

			
			

	</body>
</body>
</html>