<!-- Features 2 -->
				<div class="wrapper">
					<section class="container">
						<header class="major">
							<h2>Productos elaborados por mexicanos y con materiales mexicanos de alta calidad, eficiencia y diseño inigualable</h2>
							<p>Somos una empresa exitosa y competitiva a nivel nacional</p>
						</header>
						<div class="row features">
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured"><img src="img/catalogo/127.jpg" alt="" /></a>
								</div>
								<h3>LAMPARA CON GUIRNALDAS</h3>
								<br>
								<p>
									MOD. 127
									<br>
									Laton
								</p>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/108.jpg" alt="" /></a>
								</div>
								<h3>QUINQUE FLORENCIA</h3>
								<br>
								<p>
									MOD. 108
									<br>
									Laton / Cobre
								</p>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/118.jpg" alt="" /></a>
								</div>
								<h3>QUINQUE ADARA</h3>
								<br>
								<p>
									MOD. 118
									<br>
									Cuero Ingles
								</p>
							</section>
							<br>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/123.jpg" alt="" /></a>
								</div>
								<h3>LAMPARA HOJAS DE PARRA</h3>
								<br>
								<p>
									MOD. 123
									<br>
									Cuero Ingles
								</p>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/q127.jpg" alt="" /></a>
								</div>
								<h3>QUINQUE ANTIGUO CON GUIRNALDAS</h3>
								<br>
								<p>
									MOD. 127
									<br>
									Cafe
								</p>
							</section>
							<section class="4u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/117.jpg" alt="" /></a>
								</div>
								<h3>LAMPARA ATENAS</h3>
								<br>
								<p>
									MOD. 117
									<br>
									Cuero Ingles
								</p>
							</section>

							
							
						</div>
						<ul class="actions major">
							<li><a href="#" class="button">Conoce nuestro catalogo</a></li>
						</ul>
					</section>
				</div>