						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li>
										<a href="#">Capturas</a>
											<ul>
												<li><a href="../lideres/capturas.aspx">Lideres</a></li>
												<li><a href="../invitados/capturas.aspx">Invitados</a></li>
											</ul>
										<!-- <ul>
											<li><a href="#">Menu</a></li>
											<li><a href="#">Menu</a></li>
											<li><a href="#">Menu</a></li>
											<li>
												<a href="#">Menu</a>
												<ul>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
												</ul>
											</li>
											<li><a href="#">Menu</a></li>
										</ul> -->
									</li>
									<li><a href="#">Menu</a></li>
									<li class="break"><a href="#">Menu</a></li>
									<li><a href="#">Usuarios</a></li>
								</ul>
							</nav>
						</div>