						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li>
										<a href="#">Capturas</a>
											<ul>
												<li><a href="../lideres/capturas.aspx">Lideres</a></li>
												<li><a href="../invitados/capturas.aspx">Invitados</a></li>
											</ul>
										<!-- <ul>
											<li><a href="#">Menu</a></li>
											<li><a href="#">Menu</a></li>
											<li><a href="#">Menu</a></li>
											<li>
												<a href="#">Menu</a>
												<ul>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
													<li><a href="#">Sub Menu</a></li>
												</ul>
											</li>
											<li><a href="#">Menu</a></li>
										</ul> -->
									</li>
									<li><a href="#">Busquedas</a>
										<ul>
											<li><a href="../busLideres/busqueda.aspx">Lideres</a></li>
											<li><a href="../busInvitados/busqueda.aspx">Invitados</a></li>
											<li><a href="../buscadorX2/busqueda.aspx">Buscador</a></li>
										</ul>
									</li>
									<li class="break"><a href="#">Menu</a></li>
									<li><a href="#">Usuarios</a>
										<ul>
											<li><a href="../registro/usuarios.aspx">Alta Usuarios</a></li>
											<li><a href="../cerrar/sesion.aspx">Salir</a></li>
										</ul>
									</li>
								</ul>
							</nav>
						</div>