<!-- Productos Estrella -->
				<div class="wrapper">
					<div class="container">
						<div class="row">

							<section class="6u 12u(narrower) feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured first"><img src="img/catalogo/101.jpg" alt="" /></a>
								</div>
								<header>
									<h2>LAMPARA FLORENCIA</h2><br /><h2>
									MOD. 101</h2>
								</header>
								<p>Cuerno Ingles "Color Cuero"</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>

							<section class="6u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/104.jpg" alt="" /></a>
								</div>
								<header>
									<h2>LAMPARA FLORENCIA</h2><br /><h2>
									MOD. 104</h2>
								</header>
								<p>Laton / Cobre</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>
						</div>
					</div>

					<br>

					<div class="container">
						<div class="row">

							<section class="6u 12u(narrower) feature">
								<div class="image-wrapper first">
									<a href="#" class="image featured first"><img src="img/catalogo/237.jpg" alt="" /></a>
								</div>
								<header>
									<h2>PLAFON KAMI</h2><br /><h2>
									MOD. 237</h2>
								</header>
								<p>Chocolate</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>

							<section class="6u 12u(narrower) feature">
								<div class="image-wrapper">
									<a href="#" class="image featured"><img src="img/catalogo/240.jpg" alt="" /></a>
								</div>
								<header>
									<h2>COLGANTE KAMI</h2><br /><h2>
									MOD. 240</h2>
								</header>
								<p>Chocolate</p>
								<ul class="actions">
									<li><a href="#" class="button">Más detalles</a></li>
								</ul>
							</section>

						</div>
					</div>
				</div>